# Generated by Django 5.0 on 2023-12-20 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('echo_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='description',
            new_name='Description',
        ),
        migrations.RenameField(
            model_name='note',
            old_name='name',
            new_name='Title',
        ),
        migrations.RemoveField(
            model_name='note',
            name='title',
        ),
    ]
