# Generated by Django 5.0 on 2023-12-20 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('echo_app', '0002_rename_description_note_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='Title',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
