# Generated by Django 5.0 on 2023-12-20 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('echo_app', '0003_alter_note_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='Title',
            field=models.CharField(max_length=20),
        ),
    ]
